In [4]:
import numpy as np 
import pandas as pd
import seaborn as sns

In [5]:
df = pd.read_csv("customer.csv")
df

    age  gender   review education purchased
0    30  Female  Average    School        No
1    68  Female     Poor        UG        No
2    70  Female     Good        PG        No
3    72  Female     Good        PG        No
4    16  Female  Average        UG        No
5    31  Female  Average    School       Yes
6    18    Male     Good    School        No
7    60  Female     Poor    School       Yes
8    65  Female  Average        UG        No
9    74    Male     Good        UG       Yes
10   98  Female     Good        UG       Yes
11   74    Male     Good        UG       Yes
12   51    Male     Poor    School        No
13   57  Female  Average    School        No
14   15    Male     Poor        PG       Yes
15   75    Male     Poor        UG        No
16   59    Male     Poor        UG       Yes
17   22  Female     Poor        UG       Yes
18   19    Male     Good    School        No
19   97    Male     Poor        PG       Yes
20   57  Female  Average    School       Yes
21   32    Male  Average        PG        No
22   18  Female     Poor        PG       Yes
23   96  Female     Good    School        No
24   16  Female  Average        PG       Yes
25   57  Female     Good    School        No
26   53  Female     Poor        PG        No
27   69  Female     Poor        PG        No
28   48    Male     Poor    School        No
29   83  Female  Average        UG       Yes
30   73    Male  Average        UG        No
31   22  Female     Poor    School       Yes
32   92    Male  Average        UG       Yes
33   89  Female     Good        PG       Yes
34   86    Male  Average    School        No
35   74    Male     Poor    School       Yes
36   34  Female     Good        UG       Yes
37   94    Male  Average        PG       Yes
38   45  Female     Good    School        No
39   76    Male     Poor        PG        No
40   39    Male     Good    School        No
41   23    Male     Good        PG       Yes
42   30  Female     Good        PG       Yes
43   27    Male     Poor        PG        No
44   77  Female  Average        UG        No
45   61    Male     Poor        PG       Yes
46   64  Female     Poor        PG        No
47   38  Female     Good        PG       Yes
48   39  Female     Good        UG       Yes
49   25  Female     Good        UG        No

In [6]:
df = df.iloc[: , 2: ]
df

     review education purchased
0   Average    School        No
1      Poor        UG        No
2      Good        PG        No
3      Good        PG        No
4   Average        UG        No
5   Average    School       Yes
6      Good    School        No
7      Poor    School       Yes
8   Average        UG        No
9      Good        UG       Yes
10     Good        UG       Yes
11     Good        UG       Yes
12     Poor    School        No
13  Average    School        No
14     Poor        PG       Yes
15     Poor        UG        No
16     Poor        UG       Yes
17     Poor        UG       Yes
18     Good    School        No
19     Poor        PG       Yes
20  Average    School       Yes
21  Average        PG        No
22     Poor        PG       Yes
23     Good    School        No
24  Average        PG       Yes
25     Good    School        No
26     Poor        PG        No
27     Poor        PG        No
28     Poor    School        No
29  Average        UG       Yes
30  Average        UG        No
31     Poor    School       Yes
32  Average        UG       Yes
33     Good        PG       Yes
34  Average    School        No
35     Poor    School       Yes
36     Good        UG       Yes
37  Average        PG       Yes
38     Good    School        No
39     Poor        PG        No
40     Good    School        No
41     Good        PG       Yes
42     Good        PG       Yes
43     Poor        PG        No
44  Average        UG        No
45     Poor        PG       Yes
46     Poor        PG        No
47     Good        PG       Yes
48     Good        UG       Yes
49     Good        UG        No

In [7]:
from sklearn.model_selection import train_test_split

x_train , x_test , y_train , y_test = train_test_split(df.iloc[: , 0 : 2] , df.iloc[: , -1] , test_size = 0.2 , random_state= 42)

In [8]:
x_train.shape , x_test.shape
x_train

     review education
12     Poor    School
4   Average        UG
37  Average        PG
8   Average        UG
3      Good        PG
6      Good    School
41     Good        PG
46     Poor        PG
47     Good        PG
15     Poor        UG
9      Good        UG
16     Poor        UG
24  Average        PG
34  Average    School
31     Poor    School
0   Average    School
44  Average        UG
27     Poor        PG
33     Good        PG
5   Average    School
29  Average        UG
11     Good        UG
36     Good        UG
1      Poor        UG
21  Average        PG
2      Good        PG
43     Poor        PG
35     Poor    School
23     Good    School
40     Good    School
10     Good        UG
22     Poor        PG
18     Good    School
49     Good        UG
20  Average    School
7      Poor    School
42     Good        PG
14     Poor        PG
28     Poor    School
38     Good    School

In [9]:
from sklearn.preprocessing import OrdinalEncoder

encoder = OrdinalEncoder(categories=[
    ["Poor", "Average", "Good"],
    ["School", "UG", "PG"]
])

x_train[["review", "education"]] = encoder.fit_transform(
    x_train[["review", "education"]]
)

x_test[["review", "education"]] = encoder.transform(
    x_test[["review", "education"]]
)

In [10]:
oe_x_train = pd.DataFrame(x_train , columns = x_train.columns)
oe_x_test = pd.DataFrame(x_test , columns = x_test.columns)

In [11]:
oe_x_train

    review  education
12     0.0        0.0
4      1.0        1.0
37     1.0        2.0
8      1.0        1.0
3      2.0        2.0
6      2.0        0.0
41     2.0        2.0
46     0.0        2.0
47     2.0        2.0
15     0.0        1.0
9      2.0        1.0
16     0.0        1.0
24     1.0        2.0
34     1.0        0.0
31     0.0        0.0
0      1.0        0.0
44     1.0        1.0
27     0.0        2.0
33     2.0        2.0
5      1.0        0.0
29     1.0        1.0
11     2.0        1.0
36     2.0        1.0
1      0.0        1.0
21     1.0        2.0
2      2.0        2.0
43     0.0        2.0
35     0.0        0.0
23     2.0        0.0
40     2.0        0.0
10     2.0        1.0
22     0.0        2.0
18     2.0        0.0
49     2.0        1.0
20     1.0        0.0
7      0.0        0.0
42     2.0        2.0
14     0.0        2.0
28     0.0        0.0
38     2.0        0.0

In [ ]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

le_y_train = le.fit_transform(y_train)
le_y_test = le.transform(y_test)

le_y_train = pd.DataFrame( le_y_train,  columns=[y_train.name] )

le_y_test = pd.DataFrame( le_y_test, columns=[y_test.name] )
le_y_test

   purchased
0          0
1          0
2          0
3          1
4          1
5          1
6          0
7          0
8          1
9          1